### ISSUE TITLE
Switch to XO ESLint rules?

### ISSUE THREAD

**Issue by pdehaan** [gulpjs/eslint-config-gulp#1]
Currently we're using our own default rules in the /.eslintrc file.

In https://github.com/gulpjs/gulp/pull/1262#issuecomment-149367885 @phated suggested using the [**xo**](https://www.npmjs.com/package/xo) config (since **felixge/node-style-guide** isn't super maintained).

@sindresorhus [suggested](https://github.com/gulpjs/gulp/pull/1262#issuecomment-149705344) that we just extend the [**eslint-config-xo-space**](https://github.com/sindresorhus/eslint-config-xo-space) config and override the rules that we don't agree with; which I believe were the following ([source](https://github.com/gulpjs/gulp/pull/1262#issuecomment-149681323)):
- inconsistently quoted properties
- inline comments
- unexpected require warning
- object-curly-spacing on single key, inline objects

**Comment by phated** [comment]
@pdehaan I think we should just maintain an up to date version of node-style-guide as our ruleset. We can then change any rules we see fit.

**Comment by phated** [comment]
Did this and published as 1.0.0
