### ISSUE TITLE
space-after-keywords is deprecated since ESLint v2.0

### ISSUE THREAD

**Issue by robvenn** [gulpjs/eslint-config-gulp#10]
It should be replaced with [keyword-spacing](http://eslint.org/docs/rules/keyword-spacing). I made [a fork with this change](https://github.com/robinvenneman/eslint-config-gulp), if it's ok I can make a PR.

**Comment by pdehaan** [comment]
I think we're still using **eslint@1** (per randomly checked [**gulpjs/gulp-cli** ./package.json:59](https://github.com/gulpjs/gulp-cli/blob/9b053ed9b7a63a10777c33b86b04ed38d7f5b840/package.json#L59)).

So if we did change this deprecated rule, we should probably update ESLint to something newer.
It also looks like ESLint "dropped support for Node.js < 4" in 3.0.0, so not sure if we'd want to upgrade to **eslint@2** or **eslint@3**.

**Comment by phated** [comment]
Eventually, we'll probably upgrade to eslint@2 but we won't be upgrading to 3 because they foolishly dropped 0.10 and 0.12 support.

**Comment by yocontra** [comment]
@phated Time to update to the latest on this?

**Comment by phated** [comment]
Nah, we are going to be supporting node 0.10 at 4.0 release.  If someone wants to do the work to transition to eslint@2, I'll review the PR
