### ISSUE TITLE
Parse ES2018 even if we don't want to support it

### ISSUE THREAD

**Issue by coreyfarrell** [gulpjs/eslint-config-gulp#18]
If we are going to continue blocking ES2018 syntax I ask that we enable [node/no-unsupported-features/es-syntax](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features/es-syntax.md) here configured with `[2, {"version": ">=0.10"}]`.  The current situation is that ESLint fails to parse any ES6+, so it only reports the first issue it finds.  Updating the ESLint parser options (see #17) and adding that rule would allow ESLint to successfully parse my code changes and report a list of all errors with clearer reasons.

For example using the existing eslint-config-gulp against my current `fs-mkdirp-stream` code reports:
```
/usr/src/npm/fs-mkdirp-stream/index.js
  3:1  error  Parsing error: The keyword 'const' is reserved

/usr/src/npm/fs-mkdirp-stream/test/index.js
  5:5  error  Parsing error: Unexpected token {
```

With #17 plus the addition I'm proposing here:
```
/usr/src/npm/fs-mkdirp-stream/index.js
   3:1  error  Block-scoped variables in strict mode are not supported until Node.js 4.0.0. The configured version range is '>=0.10'  node/no-unsupported-features/es-syntax
   3:7  error  Destructuring is not supported until Node.js 6.0.0. The configured version range is '>=0.10'                           node/no-unsupported-features/es-syntax
   5:1  error  Block-scoped variables in strict mode are not supported until Node.js 4.0.0. The configured version range is '>=0.10'  node/no-unsupported-features/es-syntax
  22:5  error  Property shorthands are not supported until Node.js 4.0.0. The configured version range is '>=0.10'                    node/no-unsupported-features/es-syntax

/usr/src/npm/fs-mkdirp-stream/test/index.js
   5:5  error  Destructuring is not supported until Node.js 6.0.0. The configured version range is '>=0.10'  node/no-unsupported-features/es-syntax
  11:5  error  Destructuring is not supported until Node.js 6.0.0. The configured version range is '>=0.10'  node/no-unsupported-features/es-syntax
```

**Comment by phated** [comment]
I think this is aa good idea. I had no idea eslint had that feature.

**Comment by phated** [comment]
@coreyfarrell do you want to add that to your other PR so I can get it merged and released?

**Comment by coreyfarrell** [comment]
@phated done, also added LICENSE back to the files list.
