### ISSUE TITLE
Add a config file for the test directory

### ISSUE THREAD

**Issue by phated** [gulpjs/eslint-config-gulp#2]
Currently, some of the repos have a couple of overrides in the main .eslintrc to deal with long test names, etc.  We can put those overrides into a file that ships with this library and then add an .eslintrc to the test folder that extends the test ruleset.

**Comment by pdehaan** [comment]
Conversely you could add an .eslintrc file in the test/ directory which just overrides the parent .eslintrc file's rules.

Or yeah, add another config which adds "mocha" `env` and disables `max-len` rule (which I believe may just be a warning anyways and doesn't need to be disabled).

**Comment by phated** [comment]
@pdehaan that's what i'd like to do but as a sharable config.  You can then do:

``` json
{
  "extends": "gulp/test"
}
```

**Comment by phated** [comment]
Done and published as 1.1.0.  Thanks @pdehaan

**Comment by pdehaan** [comment]
Fixed via #3
