### ISSUE TITLE
Work together on eslint-config-defaults

### ISSUE THREAD

**Issue by baer** [gulpjs/eslint-config-gulp#7]
Hello! I wanted to propose a collaboration between this repo and https://github.com/walmartlabs/eslint-config-defaults.

I originally set out to build config-defaults because I was tired of copy pasting my eslint config around and trying to keep them up to date across lots of projects. Eslint's `extends` key fixes the distribution problem but there are still two issues:
1. Managing the eslint config file is a pain in the ass even though it is centralized. New rules are added, removed, moved and deprecated all the time and organization is terrible.
2. Just getting up and running for a new project is not straightforward anymore and I strongly believe that code quality tooling should be well suited to those who are just starting out as they're often the ones who need it most after all.

So with this project I centralized a few configs from major players, I committed to staying on top of the latest rules (and deprecations) and most importantly I made the config composable which allows them to be easily mixed and matched!

---

It's obvious that you all saw the same problems and it has been enormously helpful to a lot of people but I want to take your config one step further and I am asking for your help. With eslint-config-defaults I want to try to centralize the config from a few thought leaders around the web so that folks have fast, standard and up to date options from the start.

I've been maintaining a few "unofficial" configs for a while now but it's duplicate effort and my hope is to try to collaborate/consolidate. For my part, I am committed to staying on top of the latest rules as they change. I should mention that you all have quite a few missing rules already :).

Potential Objections(?):
- **We need quick access to the repo to make changes.** - I'm happy to try to get your maintainers added to the project.
- **The project is under walmartlabs and I'm not too sure I like that.** - It's possible we could spin this out into it's own org. No promises, I'd have to talk to legal and such about what we can do but we may be able to find a way.
- **This project is an important part of our OSS portfolio that we're not going to shut down.** - You could easily take config-defaults as a dependency and keep this exactly how it is. 

Anyway, I wanted to start a conversation and see if we can make it work for both of us.

@phated @pdehaan

**Comment by pdehaan** [comment]
@baer I think this sounds great!
I think my initial main concerns would just be potential file size issues. Currently if I install our `eslint-config-gulp` module and do a fancy `$ du -hs node_modules` it looks like our installed module is about 20K. If I create a new project and install `eslint-config-defaults`, it jumps to about 308K.
Sure, these would only be dev dependencies, but that seems like bringing in a lot of other unnecessary code into a project.

**Comment by baer** [comment]
You're absolutely right and that number would grow if more people become involved. I've never had a lot of concerns about the absolute size of dev dependencies since CI server disk space is not usually a constraint. In fact, with mocha + sinon + chai + phantom + babel under devDependencies just to get a project off the ground, a few hundred k seems like it won't make much difference. That said, I understand your wanting projects you work in to be tight - it's a good goal!

I don't really know how best to solve this so I'm open to ideas. Here are two ideas about how to solve it:
1. Keep the decomposed ESLint configs in `eslint-config-defaults` and take that as a dependency to this project. Then as a build step you could extract only the files you need and publish them. This method has a couple of disadvantages; First, you would have to publish 2 packages for every update and second you lose the decomposition unless a consumer depends on the original. It's a bit more trouble but it certainly solves the issue.
2. As a build step in `eslint-config-defaults` generate a compiled config for each project that is separately published. This also has two issues: First, it encourages a proliferation of packages on npm which could be good or bad but more importantly it suits maintainers more than it suits consumers (the main group I want to make things easier for) by making `eslint-config-defaults` more of a low level dependency than something that you'd want to use.

Happy to talk through options and eager to hear your thoughts :)

**Comment by phated** [comment]
I think scoped modules could be of benefit here.  Have the mono-repo contain all the rules and set up a publish process that publishes each separately as `@eslint-config-defaults/gulp`, etc

**Comment by baer** [comment]
I'm starting to see that it might be wise to restructure the project to allow something like the following for library authors and orginizations:

##### Starting the project
1. Create your own eslint-config-<org>
2. Take eslint-config-defaults as a devDependency
3. run eslint-config-defaults init to generate a full config with all values set to 0.
4. Turn on whatever rules you want

###### Updating a project
1. Run esling-config-defaults sync to insert new rules into your project
2. Turn on whatever you want

This seems like a slightly longer term goal since it involves all kinds of file manipulation but it would much better suit your needs and would remove the burden of a central repo. I don't have time to do this right now but Id love your thoughts.

Anyhow, I created an "unofficial" version of the gulp config here: https://github.com/walmartlabs/eslint-config-defaults/pull/51

Lets figure out the best way for you to do the publishing on that PR.

**Comment by phated** [comment]
Looks like the project was deprecated.  I'm going to close this now.
