### ISSUE TITLE
Missing critical rules

### ISSUE THREAD

**Issue by phated** [gulpjs/eslint-config-gulp#8]
I just noticed during a refactor of vinyl-fs that we are missing critical rules that I expect like [`no-undef`](http://eslint.org/docs/rules/no-undef).  @pdehaan do you think we should extend from `eslint:recommended` and adjust our ruleset from there?  /cc @contra

**Comment by yocontra** [comment]
@phated yeah, we should extend that. in the event we ever switch to es6, we should use the rackt eslint

**Comment by pdehaan** [comment]
Ah, I just missed the fact i was name checked, oh, 7 months ago.

Definitely start w/ eslint:recommended and extend from there how we/you see fit. I always like to add "eqeqeq" and some of the other common ones. But +1 to adding ESLint@4 support or whatever's recent. IIRC, we're possibly on old configs.

**Comment by phated** [comment]
@pdehaan unfortunately, we can't upgrade to newer eslint because they decided to drop 0.10 (and 0.12?) support.  But I'd like to upgrade to the last major before they did that.

**Comment by pdehaan** [comment]
OK, I think I almost understand...
Per http://eslint.org/docs/user-guide/migrating-to-3.0.0#dropping-support-for-nodejs-lt-4:

> **Dropping Support for Node.js < 4**
>
> With ESLint v3.0.0, we are dropping support for Node.js versions prior to 4. Node.js 0.10 and 0.12 are in maintenance mode and Node.js 4 is the current LTS version. If you are using an older version of Node.js, we recommend upgrading to at least Node.js 4 as soon as possible. If you are unable to upgrade to Node.js 4 or higher, then we recommend continuing to use ESLint v2.x until you are ready to upgrade Node.js.
>
> **Important:** We will not be updating the ESLint v2.x versions going forward. All bug fixes and enhancements will land in ESLint v3.x.

So it seems that **eslint@3** dropped support for Node 0.10 and 0.12.
The latest **eslint@2** release I can find is https://github.com/eslint/eslint/releases/tag/v2.13.1, which I can confirm with:

```sh
$ npm i eslint@2 -D

npm notice created a lockfile as package-lock.json. You should commit this file.

+ eslint@2.13.1
```
